//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoMatDoGuiXe
    {
        public int IDBaoCao { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> Gio { get; set; }
        public Nullable<int> TongXeVao { get; set; }
        public Nullable<int> TongXeRa { get; set; }
        public Nullable<int> ChenhLech { get; set; }
    }
}
