//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoChamCongNhanVien
    {
        public int IDBaoCao { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string TenDangNhap { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<int> ThoiGianLamViec { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
