//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoLichSuHoatDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoLichSuHoatDong()
        {
            this.CT_BaoCaoLichSuHoatDong = new HashSet<CT_BaoCaoLichSuHoatDong>();
        }
    
        public int IDBaoCao { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> HoatDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BaoCaoLichSuHoatDong> CT_BaoCaoLichSuHoatDong { get; set; }
    }
}
