//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDoanhThuThang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoDoanhThuThang()
        {
            this.CT_BaoCaoDoanhThuThang = new HashSet<CT_BaoCaoDoanhThuThang>();
        }
    
        public int IDBaoCao { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> LoaiThe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BaoCaoDoanhThuThang> CT_BaoCaoDoanhThuThang { get; set; }
    }
}
