//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BaoCaoDoanhThuThang
    {
        public int IDCTBaoCao { get; set; }
        public Nullable<int> IDBaoCao { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> TongThu { get; set; }
        public Nullable<int> TongChi { get; set; }
        public Nullable<int> ChenhLech { get; set; }
    
        public virtual BaoCaoDoanhThuThang BaoCaoDoanhThuThang { get; set; }
    }
}
