//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BaoCaoTongThu
    {
        public int IDCT_BaoCaoTongThu { get; set; }
        public Nullable<int> IDBaoCao { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<decimal> GiaTri { get; set; }
        public string HoatDong { get; set; }
    
        public virtual BaoCaoTongThu BaoCaoTongThu { get; set; }
    }
}
