//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSo
    {
        public string TenThamSo { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public int IDThamSo { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<int> GiaTriMoi { get; set; }
    }
}
