//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dekatreís_octavo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheXe
    {
        public int IDThe { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<System.DateTime> ThoiGianGui { get; set; }
        public Nullable<int> LoaiThe { get; set; }
        public Nullable<bool> Status { get; set; }
        public byte[] AnhXe1 { get; set; }
        public byte[] AnhXe2 { get; set; }
        public byte[] AnhXe3 { get; set; }
        public byte[] AnhXe4 { get; set; }
    
        public virtual LoaiThe LoaiThe1 { get; set; }
    }
}
